development:
  adapter: postgresql
  database: dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: prod
  pool: 5
  timeout: 5000
